package client;

public enum ClientState {
    MAIN_MENU,
    SINGLE_PLAYER_MENU,
    IN_SINGLE_PLAYER_GAME,
    SINGLE_PLAYER_POST_GAME,
    LOGIN_MENU,
    IN_MULTIPLAYER_GAME,
    MULTIPLAYER_POST_GAME,
    FILE_VIEWER
}
